### ISSUE TITLE
Tests failing 

### ISSUE THREAD

**Issue by kathryn1995** [klebgenomics/Kleborate#35]
I am trying to build a container for this software. I can build the container as long as I don't run the tests. Running the tests within the container also fail. 

    running test
    running egg_info
    writing Kleborate.egg-info/PKG-INFO
    writing dependency_links to Kleborate.egg-info/dependency_links.txt
    writing entry points to Kleborate.egg-info/entry_points.txt
    writing top-level names to Kleborate.egg-info/top_level.txt
    reading manifest file 'Kleborate.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Kleborate.egg-info/SOURCES.txt'
    running build_ext
    error: [Errno 2] No such file or directory: 'kaptive.py'

**Comment by kelwyres** [comment]
Hi Kathryn, 

It could be that the Kaptive submodule hasn't installed. Did you use the --recursive flag when you clones the kleborate github repo? (see here for explanation: https://github.com/katholt/Kleborate#installation)

Kelly
