### ISSUE TITLE
could not find makeblastdb

### ISSUE THREAD

**Issue by revaoleg** [klebgenomics/Kleborate#71]
Hello!
The program was properly installed on Windows (Python 3.11.4) and Linux (Python 3.9) with the latest Biopython installation. Any attempts to run the program caused the following error:
 
kleborate -o results.txt -a *.fasta
...
BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
Error: could not find makeblastdb

Is it because a Biopython version mismatch? Are there any solutions?
Have a good day!
Oleg

**Comment by revaoleg** [comment]
The problem was solved. It should be noted in the requirements that ncbi-blast+ and mash must be installed in advance.

**Comment by katholt** [comment]
thanks, this is indeed noted in the install instructions
https://github.com/klebgenomics/Kleborate/wiki/Installation
