### ISSUE TITLE
rmpA and rmpA2 alleles

### ISSUE THREAD

**Issue by valery-shap** [klebgenomics/Kleborate#74]
Hello,

thank you for creating a great tool.
If I use Kleborate, genes rmpA_2, rmpA_55* and rmpA2_8* are detected. If I use Abricate with alleles of these genes from BIGSdb (filtering: 95% -identity, 90% - coverage), I detected rmpA_2 and and rmpA2_17 only. Then I made a db for Abricate from Kleborate files "rmp_alleles.fasta" and "rmpA2.fasta" and run it again.  Coordinates of rmpA_55* and rmpA2_17 are the same. I checked a file which I uploaded from BIGsdb, there is no rmpA_55 gene and sometime they answered me that it was removed because 
"After quality-check of our scheme, we observed that the sequences were corresponding to the rmpA2 locus, thus we deleted and retired these identifiers from rmpA."

Could you please clarify a current strategy for typing these genes?
Since there are papers describing importance of rmpA2 gene, misclassifying might be a problem.

A lot of thanks,
Valery

**Comment by katholt** [comment]
Hi Valery, which version of Kleborate are you using?

@marlam89 can you please look specifically at rmpA_55 and what's going on here?

**Comment by marlam89** [comment]
Hi Valery, thank you for bringing this issue to our attention. RmpA_55, along with RmpA_54, RmpA_56 and RmpA_57 (which also had the same issues of matching to the RmpA2 variant) have now been removed from Kleborate.

**Comment by valery-shap** [comment]
Hello, @marlam89, 

Thank you very much for such a quick response. Am I right that if I install the next version of Kleborate using conda, it will be with an updated db? Now I could manually replace files.
Sorry, I have one more question. As I wrote in the first message, coordinates of rmpA55* and rmpA2_8* were the same when I checked using Abricate, and there were two copies of rmpA gene and one rmpA_2 in Kleborate report. I suppose that it meant that Kleborate detected rmpA and rmpA_2 genes with the same coordinates too and added them to a report, but I thought that if these genes have the same coordinates, only one gene should be reported. Is it right? Or does it check overlapping only within rmpA alleles (not rmpA +rmpA_2)?

A lot of thanks, 
Valery

**Comment by marlam89** [comment]
Hi Valery,

I have only ever installed Kleborate by cloning the git repo, so I'm not sure how quickly the changes propagate through conda. Alternatively, you can also do as you suggested and replace the database with the updated rmp allele file from the main branch.

Regarding your second query, if you were to now run Kleborate with the updated rmp allele database, you should only have rmpA_2 and rmpA2_8* reported. There should only ever be one match reported to any given gene but the rmpA/A2 matches get a bit tricky given the sequence similarity between the two (we have in the code removal of rmpA2 matches to an rmpA gene and vice versa, and I can see that rmpA_55 along with a few other alleles were not specified when it should have been). 

Thank you again for bringing this issue to our attention.

**Comment by valery-shap** [comment]
Thank you!

Best regards,
Valery

**Comment by valery-shap** [comment]
Hello, @marlam89,

Sorry for asking again, but I have some mismatches and I'll be very grateful, if you give some comments about this and what might be the reason for this.
I updated Kleborate to the latest version. rmpA gene is classified as "71-47%" in the Kleborate report in one isolate, but if I use Abricate with the same db, it is shown that the gene has 100% identity and 100% coverage with the same rmpA_71. 

A lot of thanks,
Valery
