### ISSUE TITLE
Kaptive not found

### ISSUE THREAD

**Issue by hkaspersen** [klebgenomics/Kleborate#75]
Hello!
I am trying to install and run the newest version of Kleborate (2.4.1) using the guide in the wiki:

```
git clone --recursive https://github.com/klebgenomics/Kleborate.git
cd Kleborate/kaptive
git pull https://github.com/klebgenomics/Kaptive master
cd ..
./kleborate-runner.py -h
```

However, when I try to run it it cannot find `kaptive.py`:

```
Error: could not find kaptive.py
```

I see some other previous issues with this was linked to not using the `--recursive` option with `git pull`. However it does not seem to work for me either way. I am working on an HPC system without root priviliges, so might I request that you perhaps consider using conda or docker in the future? It would make things much easier for many people working on HPC systems!

**Comment by tomdstanton** [comment]
Hi Hakon,

We've recently updated Kaptive to version 3, however Kleborate v2 relies on the previous version of Kaptive so I've pinned the submodule to v2.9.0 (see 8fdcc96).
Could you try installing Kleborate with:
```
git clone --recursive https://github.com/klebgenomics/Kleborate.git
./kleborate-runner.py -h
```

Cheers 😄 
Tom
