### ISSUE TITLE
Confusion in the ID of SHV

### ISSUE THREAD

**Issue by Amatatsu15** [klebgenomics/Kleborate#77]
Hi.
I'm working on some pan-genome related research, and recently I'm focusing on gene SHV.
I want to classify two kinds of SHV (as you've said in the research,  most are on chromosomal, and others are mobile) and get their base sequence, and I went to see the data in CARD. However, I failed to find some of the gene IDs like 'SHV-11.v1', which appears in the output of Kleborate.  **Would you mind telling me what '.v1' means here?**
What's more, while checking database in NCBI,  I found that there are only two kinds of blaSHV in it: SHV-1 and SHV-2. According to the result of Roary, which constructs a pan-genome and determine whether each gene is a core gene or not, SHV-1 is a core gene, while SHV-2 isn't. I guess it corresponds to the two types you mentioned in Kleborate's paper, but NCBI have already deleted the detailed information about SHV-1, so I'm not sure. **As you'd worked in this field, do you know anything more about this?**

**Comment by Amatatsu15** [comment]
please note me if I didn't express myself clear, thx

**Comment by katholt** [comment]
Apologies for the late response, I somehow missed this earlier.
The question of SHV diversity in the public databases, and in Klebsiella, and how we use this to detect and report SHV in Kleborate, is described in detail in this preprint: https://www.biorxiv.org/content/10.1101/2024.04.05.587953v1

**Comment by Amatatsu15** [comment]
Thank you so much for your reply. That helps a lot.
