### ISSUE TITLE
tabs in fasta headers

### ISSUE THREAD

**Issue by katholt** [klebgenomics/Kleborate#85]
From Corin:

I think there might be a bug in Kleborate when FASTAs have tab characters in their header. I get the following output with the attached FASTA, but if I remove all the tab characters it runs correctly.

`Error: Kleborate failed to run
Command: ['kleborate', '-a', '/tmp/query.fna', '-o', '/tmp/', '-p', 'kpsc']
Return code: 1
Standard output: strain species N50     ST      virulence_score resistance_score        num_resistance_classes  num_resistance_genes

Standard error: Traceback (most recent call last):
  File "/usr/local/bin/kleborate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kleborate/__main__.py", line 154, in main
    module_results = modules[module].get_results(unzipped_assembly, minimap2_index, args, results)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kleborate/modules/klebsiella_pneumo_complex__kaptive/klebsiella_pneumo_complex__kaptive.py", line 90, in get_results
    k_results = typing_pipeline(assembly_path, args.k_db, threads=args.threads)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kaptive/assembly.py", line 278, in typing_pipeline
    partial=a.partial, dna_seq=assembly.seq(a.ctg, a.r_st, a.r_en, a.strand))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kaptive/assembly.py", line 60, in seq
    return self.contigs[ctg].seq[start:end] if strand == "+" else self.contigs[ctg].seq[
           ~~~~~~~~~~~~^^^^^
KeyError: 'OW967300.1'`

**Comment by tomdstanton** [comment]
Issue arises from: https://github.com/klebgenomics/Kaptive/blob/8c4516fd282efa743887a539f7ab7cf9e5bbe411/kaptive/assembly.py#L100
Need to replace split(' ') to a straight-up whitespace split (on first instance).
