### ISSUE TITLE
mash install issues

### ISSUE THREAD

**Issue by kapsakcj** [klebgenomics/Kleborate#90]
This line in the `requirements.txt` may cause installation an old version mash v1.14 from pypi when running the command `pip install kleborate`

https://github.com/klebgenomics/Kleborate/blob/372d5b60b1d84c82a0507d43ae2a50833fab64cd/requirements.txt#L4

https://pypi.org/project/mash/#history

The Kleborate documentation lists that mash v2.0 or later is a dependency for kleborate.

I would recommend removing this from the requirements.txt file and you may want to suggest to users to manually install mash through another route, such as downloading the pre-compiled binary from their repo: https://github.com/marbl/Mash/releases/tag/v2.3

Or perhaps install Kleborate & mash via bioconda. ~~I'm not sure who maintains the bioconda recipe but~~ Ah I now see that you all are maintaining the bioconda recipe, sorry! It would be good to update that YAML file to install mash v2.0 or higher there as well https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kleborate/meta.yaml

**Comment by Marysteph** [comment]
Thanks @kapsakcj for the feedback. I will update YAML file to install the latest mash.
